### ISSUE TITLE
Equihash Params

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero#18]
Zero is unique in having its equihash params even now significantly harder than 144,5 that various coins are moving to. Nevertheless, let's keep track of the developments and maintain notes and links.

From Zcash team, switching params https://github.com/zcash/zcash/issues/1211#issuecomment-379882647
https://github.com/bitcartel/zcash/commit/02397b64b30916d3ff3ab0222b9b197ac3e1b9fb
https://github.com/BTCPrivate/BitcoinPrivate/pull/181

**Comment by R3DEY3UK** [comment]
**Equihash 192/7 Parameters Improvements:**

_higher time complexity
about 16 times*
higher memory requirements
about 16 times*
faster block verifications
4x
smaller solutions
400 bytes instead of 1344 bytes are inserted in every block_

**How were these parameters chosen:**

_Abandoning idea of mining on mobile devices
Making it hard enought to postpone the risk of ASICs
Memory requirements target regular desktop PCs and graphic cards with at least 8GB of RAM_

**Comment by R3DEY3UK** [comment]
**Equihash 192/7 Parameters Improvements:**
_Higher Time Complexity (x16)
Higher Memory Requirements (x16)
Faster Block Verifications (x4)
Smaller Solutions (400 bytes instead of 1344 bytes)_

**How were these parameters chosen:**
_Abandoning idea of mining on mobile devices
Making it hard enought to postpone the risk of ASICs
Memory requirements target regular desktop PCs and graphic cards with at least 8GB of RAM_

**Comment by tearodactyl** [comment]
Will not change parameters until further notice
